BookingSystem/Controllers/BookingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingSystem.Data;
using BookingSystem.DTO;
using BookingSystem.Models;
using BookingSystem.Operations;

namespace BookingSystem.Controllers
{
    public class BookingsController : Controller
    {
        private readonly BookingContext _context;
        //private int  = DatabaseManager.AddressId;

        public BookingsController(BookingContext context)
        {
            _context = context;
        }

        // GET: Bookings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Booking.ToListAsync());
        }

        // GET: Bookings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }



            var booking = await _context.Booking
                .SingleOrDefaultAsync(m => m.Id == id);


            //Pass information over so it can be sent to database and used in other categories
            BookingSystemDTO bookingsystemdto = new BookingSystemDTO();
            myBooking myShows = new myBooking();


            DatabaseManager.BookingId = booking.Id;
            myShows.PerformanceId = booking.PerformanceId;
            myShows.Name = booking.Name;
            myShows.Email = booking.Email;
            myShows.NumberFullPrice = booking.NumberFullPrice;
            myShows.NumberConcessionPrice = booking.NumberConcessionPrice;
            myShows.StoreEmail = booking.StoreEmail;

            myShows.TotalCost = (booking.NumberFullPrice * 30) + (booking.NumberConcessionPrice * 25);
            DatabaseManager.NumberOfSeats = booking.NumberFullPrice + booking.NumberConcessionPrice;

            //DatabaseManager.BookingId = (int)id;

            var allbookings = _context.Booking.ToList();
            bookingsystemdto.bookings = allbookings;


            bookingsystemdto.myBooking = myShows;

            if (booking == null)
            {
                return NotFound();
            }

            return View(bookingsystemdto);
        }

        // GET: Bookings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Bookings/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,PerformanceId,Name,Email,NumberFullPrice,NumberConcessionPrice,StoreEmail,TotalCost")] Booking booking)
        {
            BookingSystemDTO bookingsystemdto = new BookingSystemDTO();
            myBooking myShows = new myBooking();



            if (ModelState.IsValid)
            {
                _context.Add(booking);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", new {booking.Id });

            }

           

            return View(booking);
        }

        // GET: Bookings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking.SingleOrDefaultAsync(m => m.Id == id);
            if (booking == null)
            {
                return NotFound();
            }
            return View(booking);
        }

        // POST: Bookings/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,PerformanceId,Name,Email,NumberFullPrice,NumberConcessionPrice,StoreEmail,TotalCost")] Booking booking)
        {
            if (id != booking.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(booking);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BookingExists(booking.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(booking);
        }

        // GET: Bookings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var booking = await _context.Booking
                .SingleOrDefaultAsync(m => m.Id == id);
          
            if (booking == null)
            {
                return NotFound();
            }

            return View(booking);
        }

        // POST: Bookings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var booking = await _context.Booking.SingleOrDefaultAsync(m => m.Id == id);
            _context.Booking.Remove(booking);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }



        private bool BookingExists(int id)
        {
            return _context.Booking.Any(e => e.Id == id);
        }
    }
}

BookingSystem/Controllers/SeatsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingSystem.Data;
using BookingSystem.DTO;
using BookingSystem.Models;
using BookingSystem.Operations;

namespace BookingSystem.Controllers
{
    public class SeatsController : Controller
    {
        private readonly BookingContext _context;
        private int BookingID = DatabaseManager.BookingId;

        public SeatsController(BookingContext context)
        {
            _context = context;
        }

        // GET: Seats
        public async Task<IActionResult> Index()
        {
            return View(await _context.Seat.ToListAsync());
        }

        // GET: Seats/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seat = await _context.Seat
                .SingleOrDefaultAsync(m => m.Id == id);

            //Pass information over so it can be sent to database and used in other categories
            BookingSystemDTO bookingsystemdto = new BookingSystemDTO();
            mySeat mySeat = new mySeat();

            mySeat.Id = seat.Id;
            DatabaseManager.BookingId = seat.BookingId;
            mySeat.SeatNumber = seat.SeatNumber;

            var allseats = _context.Seat.ToList();
            bookingsystemdto.seats = allseats;


            bookingsystemdto.mySeat = mySeat;

            


                        if (seat == null)
            {
                return NotFound();
            }

            return View(bookingsystemdto);
        }


        // GET: Seats/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Seats/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,BookingId,SeatNumber")] Seat seat)
        {


            if (ModelState.IsValid)
                DatabaseManager.NumberOfSeats = DatabaseManager.NumberOfSeats - 1;
            



               
                {
                    _context.Add(seat);
                    await _context.SaveChangesAsync();
                    if (DatabaseManager.NumberOfSeats <= 0)
                    {
                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                    return RedirectToAction(nameof(Create));
                }
                }

                return View(seat);
            


          
        }

        // GET: Seats/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seat = await _context.Seat.SingleOrDefaultAsync(m => m.Id == id);
            if (seat == null)
            {
                return NotFound();
            }
            return View(seat);
        }

        // POST: Seats/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,BookingId,SeatNumber")] Seat seat)
        {
            if (id != seat.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seat);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SeatExists(seat.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(seat);
        }

        // GET: Seats/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seat = await _context.Seat
                .SingleOrDefaultAsync(m => m.Id == id);
            if (seat == null)
            {
                return NotFound();
            }

            return View(seat);
        }

        // POST: Seats/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seat = await _context.Seat.SingleOrDefaultAsync(m => m.Id == id);
            _context.Seat.Remove(seat);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Complete()
        {
            return View();
        }

        private bool SeatExists(int id)
        {
            return _context.Seat.Any(e => e.Id == id);
        }
    }
}

BookingSystem/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingSystem.Data;
using BookingSystem.DTO;
using BookingSystem.Models;
using BookingSystem.Operations;

namespace BookingSystem.Controllers
{
    public class ShowsController : Controller
    {
        private readonly BookingContext _context;

        public ShowsController(BookingContext context)
        {
            _context = context;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shows.ToListAsync());
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var shows = await _context.Shows
                .SingleOrDefaultAsync(m => m.Id == id);


            //Pass information over so it can be sent to database and used in other categories
            BookingSystemDTO bookingsystemdto = new BookingSystemDTO();
            myShow myShows = new myShow();

            DatabaseManager.ShowId = shows.Id;
            DatabaseManager.ShowName = shows.Name;
            myShows.EndDate = shows.EndDate;
            DatabaseManager.FullPrice = shows.FullPrice;
            DatabaseManager.ConcessionPrice = shows.ConcessionPrice;
            

         


            

            var allshows = _context.Shows.ToList();
            bookingsystemdto.shows = allshows;


            bookingsystemdto.myShows = myShows;

            //var shows = await _context.Shows
            //    .SingleOrDefaultAsync(m => m.Id == id);
            if (shows == null)
            {
                return NotFound();
            }

            return View(shows);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,EndDate,FullPrice,ConcessionPrice")] Shows shows)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shows);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shows);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shows = await _context.Shows.SingleOrDefaultAsync(m => m.Id == id);
            if (shows == null)
            {
                return NotFound();
            }
            return View(shows);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,EndDate,FullPrice,ConcessionPrice")] Shows shows)
        {
            if (id != shows.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shows);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowsExists(shows.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shows);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shows = await _context.Shows
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shows == null)
            {
                return NotFound();
            }

            return View(shows);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shows = await _context.Shows.SingleOrDefaultAsync(m => m.Id == id);
            _context.Shows.Remove(shows);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowsExists(int id)
        {
            return _context.Shows.Any(e => e.Id == id);
        }
    }
}

BookingSystem/Views/Shared/_AdminPage.cshtml
@using Microsoft.AspNetCore.Identity
@using BookingSystem.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            @*<li>
                <a asp-area="" asp-controller="Manage" asp-action="Index" title="Manage">Hello You!</a>
            </li>*@
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Log out</button>
            </li>
            <li>
            @*<li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>*@
            <li><a asp-area="" asp-controller="Shows" asp-action="Index">Shows</a></li>
            <li><a asp-area="" asp-controller="Performances" asp-action="Index">Performances</a></li>
            <li><a asp-area="" asp-controller="Bookings" asp-action="Index">Bookings</a></li>
            <li><a asp-area="" asp-controller="Seats" asp-action="Index">Seats</a></li>
            </li>
        </ul>
    </form>
}
else
{
    <ul class="nav navbar-nav navbar-right">
        <li><a asp-area="" asp-controller="Performances" asp-action="Index">Book Performance</a></li>
    </ul>
}

@*@if (SignInManager.IsSignedIn(User))
{
   
}*@

BookingSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookingSystem</title>

    <environment include="Development">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        @*<link rel="stylesheet" href="~/css/site.css" />*@
        <link rel="stylesheet" href="~/css/freelancer.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>
</head>



<body id="page-top" class="index">
    <div id="skipnav"><a href="#maincontent">Skip to main content</a></div>

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <!-- <a class="navbar-brand" href="#page-top">Start Bootstrap</a> -->
                <a asp-area="" asp-controller="Account" asp-action="Login"><img src="/img/logo.png" height="60"></a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right"></ul>
                @await Html.PartialAsync("_AdminPage")
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>
    
    <section id="portfolio">
        <div class="container" id="maincontent=" tabindex="-1">
            @RenderBody()




        </div>
    </section>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>