BookingSystem/Models/Shows.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace BookingSystem.Models
{
    public class Shows
    {
        public int Id { get; set; }
        public string Name { get; set; }
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }  
        public Decimal FullPrice { get; set; }
        public Decimal ConcessionPrice { get; set; }

    }
}

BookingSystem/Controllers/PerformancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingSystem.Data;
using BookingSystem.Models;
using BookingSystem.DTO;
using BookingSystem.Operations;
namespace BookingSystem.Controllers

{
    public class PerformancesController : Controller
    {
        private readonly BookingContext _context;

        public PerformancesController(BookingContext context)
        {
            _context = context;
        }

        // GET: Performances
        public async Task<IActionResult> Index()
        {
            return View(await _context.Performances.ToListAsync());
        }

        // GET: Performances/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performances = await _context.Performances
                .SingleOrDefaultAsync(m => m.Id == id);


            //Pass information over so it can be sent to database and used in other categories
            BookingSystemDTO bookingsystemdto = new BookingSystemDTO();
            myPerformance myPerformances = new myPerformance();

            DatabaseManager.PerformanceId = performances.Id;

            DatabaseManager.ShowId = performances.ShowId;








            var allperformances = _context.Performances.ToList();
            bookingsystemdto.performances = allperformances;


            bookingsystemdto.myPerformances = myPerformances;

            if (performances == null)
            {
                return NotFound();
            }

            return View(performances);
        }

        // GET: Performances/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Performances/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,ShowId,Date")] Performances performances)
        {
            if (ModelState.IsValid)
            {
                _context.Add(performances);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(performances);
        }

        // GET: Performances/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performances = await _context.Performances.SingleOrDefaultAsync(m => m.Id == id);
            if (performances == null)
            {
                return NotFound();
            }
            return View(performances);
        }

        // POST: Performances/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,ShowId,Date")] Performances performances)
        {
            if (id != performances.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(performances);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PerformancesExists(performances.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(performances);
        }

        // GET: Performances/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var performances = await _context.Performances
                .SingleOrDefaultAsync(m => m.Id == id);
            if (performances == null)
            {
                return NotFound();
            }

            return View(performances);
        }

        // POST: Performances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var performances = await _context.Performances.SingleOrDefaultAsync(m => m.Id == id);
            _context.Performances.Remove(performances);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PerformancesExists(int id)
        {
            return _context.Performances.Any(e => e.Id == id);
        }
    }
}

BookingSystem/Controllers/ShowsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BookingSystem.Data;
using BookingSystem.DTO;
using BookingSystem.Models;
using BookingSystem.Operations;

namespace BookingSystem.Controllers
{
    public class ShowsController : Controller
    {
        private readonly BookingContext _context;

        public ShowsController(BookingContext context)
        {
            _context = context;
        }

        // GET: Shows
        public async Task<IActionResult> Index()
        {
            return View(await _context.Shows.ToListAsync());
        }

        // GET: Shows/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var shows = await _context.Shows
                .SingleOrDefaultAsync(m => m.Id == id);


            //Pass information over so it can be sent to database and used in other categories
            BookingSystemDTO bookingsystemdto = new BookingSystemDTO();
            myShow myShows = new myShow();

            DatabaseManager.ShowId = shows.Id;
            DatabaseManager.ShowName = shows.Name;
            myShows.EndDate = shows.EndDate;
            DatabaseManager.FullPrice = shows.FullPrice;
            DatabaseManager.ConcessionPrice = shows.ConcessionPrice;
            

         


            

            var allshows = _context.Shows.ToList();
            bookingsystemdto.shows = allshows;


            bookingsystemdto.myShows = myShows;

            //var shows = await _context.Shows
            //    .SingleOrDefaultAsync(m => m.Id == id);
            if (shows == null)
            {
                return NotFound();
            }

            return View(shows);
        }

        // GET: Shows/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Shows/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,EndDate,FullPrice,ConcessionPrice")] Shows shows)
        {
            if (ModelState.IsValid)
            {
                _context.Add(shows);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(shows);
        }

        // GET: Shows/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shows = await _context.Shows.SingleOrDefaultAsync(m => m.Id == id);
            if (shows == null)
            {
                return NotFound();
            }
            return View(shows);
        }

        // POST: Shows/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,EndDate,FullPrice,ConcessionPrice")] Shows shows)
        {
            if (id != shows.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(shows);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ShowsExists(shows.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(shows);
        }

        // GET: Shows/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var shows = await _context.Shows
                .SingleOrDefaultAsync(m => m.Id == id);
            if (shows == null)
            {
                return NotFound();
            }

            return View(shows);
        }

        // POST: Shows/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var shows = await _context.Shows.SingleOrDefaultAsync(m => m.Id == id);
            _context.Shows.Remove(shows);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ShowsExists(int id)
        {
            return _context.Shows.Any(e => e.Id == id);
        }
    }
}

BookingSystem/Views/Shows/Create.cshtml
@model BookingSystem.Models.Shows

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Shows</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>

                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" type="date" value="@DateTime.Now.ToString("dd/MM/yyyy")" data-date-format="dd/mm/yyyy" class="form-control" />

                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullPrice" class="control-label"></label>
                <input asp-for="FullPrice" class="form-control" />
                <span asp-validation-for="FullPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConcessionPrice" class="control-label"></label>
                <input asp-for="ConcessionPrice" class="form-control" />
                <span asp-validation-for="ConcessionPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookingSystem/Views/Shows/Delete.cshtml
@model BookingSystem.Models.Shows

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Shows</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ConcessionPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ConcessionPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

BookingSystem/Views/Shows/Details.cshtml
@model BookingSystem.Models.Shows

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Shows</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.FullPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.FullPrice)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ConcessionPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ConcessionPrice)
        </dd>
    </dl>
    <a asp-controller="Performances" asp-action="Create">Select Performances</a>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

BookingSystem/Views/Shows/Edit.cshtml
@model BookingSystem.Models.Shows

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Shows</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" type="date" value="@DateTime.Now.ToString("dd/MM/yyyy")" data-date-format="dd/mm/yyyy" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FullPrice" class="control-label"></label>
                <input asp-for="FullPrice" class="form-control" />
                <span asp-validation-for="FullPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ConcessionPrice" class="control-label"></label>
                <input asp-for="ConcessionPrice" class="form-control" />
                <span asp-validation-for="ConcessionPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

BookingSystem/Views/Shows/Index.cshtml
@model IEnumerable<BookingSystem.Models.Shows>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.EndDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.FullPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ConcessionPrice)
                </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
               
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EndDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FullPrice)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ConcessionPrice)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>